[package]
name = "binsync"
description = "A library for syncing binary files between two locations."
version = "0.0.1"
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/dristic/binsync"
readme = "README.md"
exclude = ["examples/*", ".github/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler32 = "1.2.0"
bincode = "1.3.3"
clap = "2.33.3"
ctrlc = "3.2.1"
interprocess = "1.1.1"
md5 = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
simd-adler32 = "0.3.3"
walkdir = "2"
